# Generated by Django 4.0.2 on 2022-11-08 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_alter_categorymodel_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, unique=True)),
                ('product_slug', models.SlugField(max_length=100, unique=True)),
                ('product_description', models.TextField(blank=True)),
                ('product_price', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='photoes/products')),
                ('product_stock', models.IntegerField()),
                ('product_is_available', models.BooleanField(default=True)),
                ('product_created_date', models.DateTimeField(auto_now_add=True)),
                ('product_modified_date', models.DateTimeField(auto_now=True)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.categorymodel')),
            ],
        ),
    ]
