# Generated by Django 4.0.2 on 2022-11-10 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name': 'Product models', 'verbose_name_plural': 'Products'},
        ),
    ]
