# Generated by Django 4.0.2 on 2022-11-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='category_slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
